services:
  postgres:
    image: postgres:16
    container_name: devops-platform-postgres
    restart: unless-stopped

    environment:
      POSTGRES_DB: devops_db
      POSTGRES_USER: devops_user
      POSTGRES_PASSWORD: devops_password

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    image: devops-platform:local
    container_name: devops-platform-backend
    restart: unless-stopped

    environment:
      DATABASE_URL: postgresql://devops_user:devops_password@postgres:5432/devops_db

    ports:
      - "8000:8000"

    depends_on:
      - postgres

volumes:
  postgres_data:
